In [4]:
import math
import numpy as np

In [5]:
a1z=650
a2x=400
a2z=680
a3z=1100
a4z=230
a4x=766
a5x=345
a6x=244

In [8]:
A=250*math.pi/180
B=0*math.pi/180
C=-90*math.pi/180
X=600
Y=-1000
Z=3300
# X=1755
# Y=0
# Z=2660

In [9]:
# Forming rotation matrix from A, B, C

R=np.array([[np.cos(C)*np.cos(B),np.cos(C)*np.sin(B)*np.sin(A)-np.sin(C)*np.cos(A),np.cos(C)*np.sin(B)*np.cos(A)+np.sin(C)*np.sin(A)],[np.sin(C)*np.cos(B),np.cos(C)*np.cos(A)+np.sin(C)*np.sin(B)*np.sin(A),np.sin(C)*np.sin(B)*np.cos(A)-np.cos(C)*np.sin(A)],[-np.sin(B),np.cos(B)*np.sin(A),np.cos(B)*np.cos(A)]])
print(R)

[[ 6.12323400e-17 -3.42020143e-01  9.39692621e-01]
 [-1.00000000e+00 -2.09426937e-17  5.75395780e-17]
 [-0.00000000e+00 -9.39692621e-01 -3.42020143e-01]]


In [10]:
# Finding the wrist point

WPx=X-a6x*(R[0,0])
WPy=Y-a6x*(R[1,0])
WPz=Z-a6x*(R[2,0])
# print(WPx)
# print(WPy)
# print(WPz)

In [11]:
# Calculating J2

WPxy=math.sqrt((WPx**2)+(WPy**2))
l=WPxy-a2x # + or - a2x
h=WPz-a1z-a2z
rho=math.sqrt(h**2+l**2)
b4x=math.sqrt(a4z**2+((a4x+a5x)**2))
# print(WPxy)
# print(l)
# print(h)
# print(rho)
# print(b4x)

In [12]:
if(rho<a3z+b4x):
    if(rho>a3z-b4x):
        print("OK")
else:
    print("error")

OK


In [13]:
#Calculate J1 in radian and degrees

J1=math.atan2(WPy,WPx)
print("J1 in radian: ", J1)
J1deg=(J1*180/math.pi)
print("J1 in degrees: ", J1deg)

J1 in radian:  -0.8999388601941296
J1 in degrees:  -51.562698508937466


In [14]:
alpha=math.atan2(h,l)
cos_beta=(((rho**2)+(a3z**2)-(b4x**2))/(2*rho*a3z))
beta=math.atan2(math.sqrt(1-(cos_beta**2)),cos_beta)
J2=(math.pi/2)-(alpha)-(beta) #+ or - beta
print("J2 in radian: ", J2)
J2deg=(J2*180/math.pi)
print("J2 in degrees: ", J2deg)
# print(alpha)
# print(beta)

J2 in radian:  -0.13727291358291166
J2 in degrees:  -7.865158589764911


In [15]:
delta=math.atan2(a5x+a4x,a4z)
cos_gama=(((a3z**2)+(b4x**2)-(rho**2))/(2*b4x*a3z))
gama=math.atan2(math.sqrt(1-(cos_gama**2)),cos_gama)
J3=(math.pi)-(delta)-(gama)
print("J3 in radian: ", J3)
J3deg=(J3*180/math.pi)
print("J3 in degrees: ", J3deg)

J3 in radian:  -0.5467928426202202
J3 in degrees:  -31.328922150099658


In [16]:
Rarm = np.array([[np.cos(J1)*np.cos(J2+J3),-np.sin(J1),np.cos(J1)*np.sin(J2+J3)],[np.sin(J1)*np.cos(J2+J3),np.cos(J1),np.sin(J1)*np.sin(J2+J3)],[-np.sin(J2+J3),0,np.cos(J2+J3)]])
print(Rarm)
Rarmtranspose=Rarm.transpose()
# print(Rarmtranspose)

[[ 0.48179092  0.7832889  -0.39285621]
 [-0.60705656  0.62165786  0.49499883]
 [ 0.63194924  0.          0.77500978]]


In [17]:
R_wrist=Rarmtranspose@R
print(R_wrist)
# print(R)

[[ 0.60705656 -0.75862024  0.236596  ]
 [-0.62165786 -0.26790058  0.7360508 ]
 [-0.49499883 -0.59390623 -0.63423304]]


In [18]:
J4=math.atan2(R_wrist[1,0],-R_wrist[2,0])
print("J4 in radian: ", J4)
J4deg=(J4*180/math.pi)
print("J4 in degrees: ", J4deg)

J4 in radian:  -0.8983424590149133
J4 in degrees:  -51.47123145895867


In [19]:
J5=math.atan2(math.sqrt(1-(R_wrist[0,0]**2)),R_wrist[0,0])
print("J5 in radian: ", J5)
J5deg=(J5*180/math.pi)
print("J5 in degrees: ", J5deg)

J5 in radian:  0.9184450300545653
J5 in degrees:  52.62302393689264


In [23]:
J6=math.atan2(R_wrist[0,1],R_wrist[0,2])
print("J6 in radian: ", J6)
J6deg=(J6*180/math.pi)
print("J6 in degrees: ", J6deg)

J6 in radian:  -1.2684793720808196
J6 in degrees:  -72.67851441963576
